# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Lorena/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Lorena/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Lorena/src/CMakeFiles /home/pi/Lorena/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Lorena/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named START.ELF

# Build rule for target.
START.ELF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 START.ELF
.PHONY : START.ELF

# fast build rule for target.
START.ELF/fast:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/build
.PHONY : START.ELF/fast

# target to build an object file
start/ND_GDT.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_GDT.o
.PHONY : start/ND_GDT.o

# target to preprocess a source file
start/ND_GDT.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_GDT.i
.PHONY : start/ND_GDT.i

# target to generate assembly for a file
start/ND_GDT.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_GDT.s
.PHONY : start/ND_GDT.s

# target to build an object file
start/ND_IDT.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_IDT.o
.PHONY : start/ND_IDT.o

# target to preprocess a source file
start/ND_IDT.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_IDT.i
.PHONY : start/ND_IDT.i

# target to generate assembly for a file
start/ND_IDT.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_IDT.s
.PHONY : start/ND_IDT.s

# target to build an object file
start/ND_IRQ.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_IRQ.o
.PHONY : start/ND_IRQ.o

# target to preprocess a source file
start/ND_IRQ.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_IRQ.i
.PHONY : start/ND_IRQ.i

# target to generate assembly for a file
start/ND_IRQ.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_IRQ.s
.PHONY : start/ND_IRQ.s

# target to build an object file
start/ND_ISR.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_ISR.o
.PHONY : start/ND_ISR.o

# target to preprocess a source file
start/ND_ISR.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_ISR.i
.PHONY : start/ND_ISR.i

# target to generate assembly for a file
start/ND_ISR.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_ISR.s
.PHONY : start/ND_ISR.s

# target to build an object file
start/ND_Keyboard.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Keyboard.o
.PHONY : start/ND_Keyboard.o

# target to preprocess a source file
start/ND_Keyboard.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Keyboard.i
.PHONY : start/ND_Keyboard.i

# target to generate assembly for a file
start/ND_Keyboard.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Keyboard.s
.PHONY : start/ND_Keyboard.s

# target to build an object file
start/ND_Memory.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Memory.o
.PHONY : start/ND_Memory.o

# target to preprocess a source file
start/ND_Memory.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Memory.i
.PHONY : start/ND_Memory.i

# target to generate assembly for a file
start/ND_Memory.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Memory.s
.PHONY : start/ND_Memory.s

# target to build an object file
start/ND_Panic.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Panic.o
.PHONY : start/ND_Panic.o

# target to preprocess a source file
start/ND_Panic.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Panic.i
.PHONY : start/ND_Panic.i

# target to generate assembly for a file
start/ND_Panic.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Panic.s
.PHONY : start/ND_Panic.s

# target to build an object file
start/ND_Ports.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Ports.o
.PHONY : start/ND_Ports.o

# target to preprocess a source file
start/ND_Ports.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Ports.i
.PHONY : start/ND_Ports.i

# target to generate assembly for a file
start/ND_Ports.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Ports.s
.PHONY : start/ND_Ports.s

# target to build an object file
start/ND_Screen.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Screen.o
.PHONY : start/ND_Screen.o

# target to preprocess a source file
start/ND_Screen.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Screen.i
.PHONY : start/ND_Screen.i

# target to generate assembly for a file
start/ND_Screen.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Screen.s
.PHONY : start/ND_Screen.s

# target to build an object file
start/ND_String.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_String.o
.PHONY : start/ND_String.o

# target to preprocess a source file
start/ND_String.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_String.i
.PHONY : start/ND_String.i

# target to generate assembly for a file
start/ND_String.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_String.s
.PHONY : start/ND_String.s

# target to build an object file
start/ND_Timer.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Timer.o
.PHONY : start/ND_Timer.o

# target to preprocess a source file
start/ND_Timer.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Timer.i
.PHONY : start/ND_Timer.i

# target to generate assembly for a file
start/ND_Timer.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/ND_Timer.s
.PHONY : start/ND_Timer.s

# target to build an object file
start/NextKernel_Main.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/NextKernel_Main.o
.PHONY : start/NextKernel_Main.o

# target to preprocess a source file
start/NextKernel_Main.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/NextKernel_Main.i
.PHONY : start/NextKernel_Main.i

# target to generate assembly for a file
start/NextKernel_Main.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/NextKernel_Main.s
.PHONY : start/NextKernel_Main.s

# target to build an object file
start/NextShellLite.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/NextShellLite.o
.PHONY : start/NextShellLite.o

# target to preprocess a source file
start/NextShellLite.i:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/NextShellLite.i
.PHONY : start/NextShellLite.i

# target to generate assembly for a file
start/NextShellLite.s:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/NextShellLite.s
.PHONY : start/NextShellLite.s

# target to build an object file
start/boot.o:
	$(MAKE) -f CMakeFiles/START.ELF.dir/build.make CMakeFiles/START.ELF.dir/start/boot.o
.PHONY : start/boot.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... START.ELF"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... start/ND_GDT.o"
	@echo "... start/ND_GDT.i"
	@echo "... start/ND_GDT.s"
	@echo "... start/ND_IDT.o"
	@echo "... start/ND_IDT.i"
	@echo "... start/ND_IDT.s"
	@echo "... start/ND_IRQ.o"
	@echo "... start/ND_IRQ.i"
	@echo "... start/ND_IRQ.s"
	@echo "... start/ND_ISR.o"
	@echo "... start/ND_ISR.i"
	@echo "... start/ND_ISR.s"
	@echo "... start/ND_Keyboard.o"
	@echo "... start/ND_Keyboard.i"
	@echo "... start/ND_Keyboard.s"
	@echo "... start/ND_Memory.o"
	@echo "... start/ND_Memory.i"
	@echo "... start/ND_Memory.s"
	@echo "... start/ND_Panic.o"
	@echo "... start/ND_Panic.i"
	@echo "... start/ND_Panic.s"
	@echo "... start/ND_Ports.o"
	@echo "... start/ND_Ports.i"
	@echo "... start/ND_Ports.s"
	@echo "... start/ND_Screen.o"
	@echo "... start/ND_Screen.i"
	@echo "... start/ND_Screen.s"
	@echo "... start/ND_String.o"
	@echo "... start/ND_String.i"
	@echo "... start/ND_String.s"
	@echo "... start/ND_Timer.o"
	@echo "... start/ND_Timer.i"
	@echo "... start/ND_Timer.s"
	@echo "... start/NextKernel_Main.o"
	@echo "... start/NextKernel_Main.i"
	@echo "... start/NextKernel_Main.s"
	@echo "... start/NextShellLite.o"
	@echo "... start/NextShellLite.i"
	@echo "... start/NextShellLite.s"
	@echo "... start/boot.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

